name: Deployment

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install NPM
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run test
        run: npm test

      - name: Call workflow
        if: github.event_name == 'pull_request' && github.event.label.name == 'deployment'
        uses: ./.github/workflows/runner.yml
        with:
          branch: ${{ github.head_ref }}
          environment: production

      - name: Deploy to GitHub Pages
        if: github.event.push
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: production # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
